# Generated by Django 3.2.7 on 2021-11-06 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20211019_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 13, 43, 37, 294409), verbose_name='تاریخ پرداخت')),
                ('state', models.SmallIntegerField(choices=[(1, 'پرداخت نشده'), (2, 'در انتظار پرداخت'), (3, 'پرداخت شده')], default=1, verbose_name='وضعیت پرداخت')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 11, 6, 13, 43, 37, 294451), verbose_name='تاریخ ایجاد')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
        ),
        migrations.CreateModel(
            name='FactorProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی')),
                ('id_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factor.factors', verbose_name='فاکتور')),
                ('id_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='نام محصول')),
            ],
        ),
    ]
