# Generated by Django 3.2.7 on 2021-11-06 14:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 14, 3, 27, 670272, tzinfo=utc), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 14, 3, 27, 670193, tzinfo=utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
