# Generated by Django 3.2.7 on 2021-10-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20211019_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('id_user', models.IntegerField(verbose_name='User ID')),
                ('count', models.PositiveIntegerField(verbose_name='count')),
                ('total_price', models.PositiveIntegerField(verbose_name='Total price')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Product ID')),
            ],
        ),
    ]
