# Generated by Django 3.2.7 on 2021-10-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='تعداد محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='دسته بندی')),
            ],
        ),
    ]
