# Generated by Django 3.2.7 on 2021-10-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, verbose_name='محصول حذف شده'),
        ),
    ]
