# Generated by Django 3.2.7 on 2021-10-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategories', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد محصول'),
        ),
    ]
