# Generated by Django 3.2.7 on 2021-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211019_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(default='/static/img/products.jpg', upload_to='products/'),
        ),
    ]
