# Generated by Django 3.2.7 on 2021-12-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='picture',
        ),
    ]
